Repository egeakman/CovidTurkey, pull requests merged in 2021-12, with the labels that each got.

#1 New class structure
  src/CovidTurkey.py
  tests/test_get_func.py
Labels: structure

#3 Fix __dir__() issue by simply reverting
  src/CovidTurkey.py
  src/functions.py
  tests/test_get_func.py
Labels: bug

#4 Add Python Tests
  .github/workflows/linux_tests.yml
  .github/workflows/windows_tests.yml
  requirements.txt
  src/CovidTurkey.py
  src/functions.py
  tests/test_cases.py
  tests/test_dr.py
  tests/test_get_func.py
  tests/test_vax.py
Labels: enhancement

#5 Add macOS tests.
  .github/workflows/macos_tests.yml
Labels: enhancement

#6 Add an option for formatting the results
  src/CovidTurkey.py
  src/functions.py
  tests/test_cases.py
  tests/test_dr.py
  tests/test_vax.py
Labels: bug, enhancement

#9 Optimize performance by enabling caching
  requirements.txt
  src/CovidTurkey.py
  src/functions.py
Labels: enhancement

#14 Fix the problem that causes tests to fail
  .github/workflows/linux_tests.yml
  .github/workflows/macos_tests.yml
  .github/workflows/windows_tests.yml
  src/CovidTurkey.py
  src/functions.py
  tests/test_cases.py
  tests/test_dr.py
  tests/test_vax.py
Labels: optimization, enhancement, bug
